name: nvip
description: An Immunization Information System application for the GoK-MoH vaccination department.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.3.1+1
  firebase_messaging: ^4.0.0+1
  firebase_analytics: ^2.0.2+1
  charts_flutter: ^0.6.0
  rounded_modal: ^1.0.0
  fluttertoast: ^3.0.1
  intl: ^0.15.7
  http: ^0.12.0+1
  sqflite: ^1.1.1
  path_provider: ^0.5.0+1
  shared_preferences: ^0.5.1+1
  connectivity: ^0.4.2
  flutter_appavailability: ^0.0.21
  device_calendar: ^0.1.0
  image_picker: ^0.5.0+3
  flutter_typeahead: ^1.1.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/lake.jpg
    - images/no_image.png
    - images/avator.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Bree_Serif
      fonts:
        - asset: fonts/Bree_Serif/BreeSerif-Regular.ttf
          weight: 400
    - family: Courgette
      fonts:
        - asset: fonts/Courgette/Courgette-Regular.ttf
          weight: 400
    - family: Dancing_Script
      fonts:
        - asset: fonts/Dancing_Script/DancingScript-Bold.ttf
          weight: 700
        - asset: fonts/Dancing_Script/DancingScript-Regular.ttf
          weight: 400
    - family: Felipa
      fonts:
        - asset: fonts/Felipa/Felipa-Regular.ttf
          weight: 400
    - family: Kalam
      fonts:
        - asset: fonts/Kalam/Kalam-Bold.ttf
          weight: 700
        - asset: fonts/Kalam/Kalam-Light.ttf
          weight: 300
        - asset: fonts/Kalam/Kalam-Regular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 900
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Italic.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 100
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy/Satisfy-Regular.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
